spring.application.name=ToDoList

spring.datasource.url=jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Configuracao para carregar dados iniciais
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=

projeto.jwtSecret=ykCl2h4s8HMqrWor1QYE0ZknxVTbHJG4uScASHQsvDZcWw1RgJ3E0I7IU9C2b3NBUciQwM2RZltHCGv2OU+teA==

projeto.jwtExpirationInMs=900000